# Example workflow running in windows-2022 when dispatched
name: Test WSL

on:
  workflow_dispatch:

jobs:
  test-wsl-execution:
    name: Test WSL
    runs-on: windows-2025
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run on WSL
        uses: Vampire/setup-wsl@f40fb59d850112c9a292b0218bca8271305b9127
        with:
          distribution: Ubuntu-24.04
          set-as-default: true
          use-cache: true
          wsl-conf: |
            [boot]
            systemd=true
          wsl-shell-user: runner
          wsl-version: 2

      - name: Copy script
        shell: wsl-bash {0}
        run: |
          cp "$(wslpath -a -u '${{ github.workspace }}/test.sh')" test.sh
          chmod a+x test.sh

      - name: Run script
        shell: wsl-bash {0}
        run: |
          ./test.sh